print('Enter the name of Cat 1:')
cat1 = input()
print('Enter the name of Cat 2:')
cat2 = input()
print('Enter the name of Cat 3:')
cat3 = input()
print('Enter the name of Cat 4:')
cat4 = input()
print('Enter the name of Cat 5:')
cat5 = input()
print('Enter the name of Cat 6:')
cat6 = input()

print("The cats names are:")
print(cat1 + ' ' + cat2 + ' ' + cat3 + ' ' + cat4 + ' ' + cat5 + ' ' + cat6)